version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - uploads:/app/uploads
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql
    
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  uploads:
  mysql_data: